title: Desarrollo Web NodeJS • Quito Ecuador
description: Desarrollo Web NodeJS en Quito Ecuador Desarrollo Diseño Fotografía Asistencia Expertos Móvil y Web
url: "https://desarrollowebnodejs.github.io" 
author:
    nombre: Vladimir Rodríguez
    email: fizzvr@gmail.com
    twitter_username: fizzvr
    github_username:  fizzvr
disqus:
repository: DesarrolloWebNodeJS/desarrollowebnodejs.github.io
google_analytics: A-222234
rss: true
permalink: /2033/:categories/:title/
paginate: 1
markdown: kramdown
feed:
    path: feed.xml
sass:
   style: compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
    - npm-debug.log
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - package.json
    - bower.json
    - node_modules
    - bower_components
    - Gruntfile.js
    - vendor
    - LICENCIA
    - yarn.lock